// Bungee Contingent Payment & Referral Residual Engine
// ------------------------------------------------------
// All money math is done in integer CENTS to avoid floating-point drift,
// then converted to dollars only at the boundary. This guarantees precise
// decimal figures for every transaction and residual calculation.

// ---- Fee structure -------------------------------------------------------

// Flat contingent service fee charged on top of the worker payment.
export const SERVICE_FEE_RATE = 0.3 // 30%

export interface TransactionBreakdown {
  workerPayment: number // $X — what the Bungee/worker is paid
  serviceFee: number // $Y — 30% contingent platform fee
  totalCost: number // $X + $Y — total charged to the business
  feeRate: number // 0.30, exposed for display
}

/** Round a cents value (may be fractional) to a whole cent. */
function roundCents(cents: number): number {
  return Math.round(cents)
}

/** Convert a dollar amount to integer cents. */
function toCents(dollars: number): number {
  return Math.round(dollars * 100)
}

/** Convert integer cents back to a dollar number with 2-decimal precision. */
function toDollars(cents: number): number {
  return roundCents(cents) / 100
}

/**
 * Core transaction breakdown.
 * Given the worker payment, computes the 30% service fee and total cost
 * to the business with exact cent precision.
 */
export function computeTransaction(workerPayment: number): TransactionBreakdown {
  const workerCents = toCents(workerPayment)
  const feeCents = roundCents(workerCents * SERVICE_FEE_RATE)
  const totalCents = workerCents + feeCents

  return {
    workerPayment: toDollars(workerCents),
    serviceFee: toDollars(feeCents),
    totalCost: toDollars(totalCents),
    feeRate: SERVICE_FEE_RATE,
  }
}

// ---- 18-month residual schedule -----------------------------------------

// The referrer earns a percentage OF THE 30% SERVICE FEE, tiered by how many
// months the referred account has been active.
export interface ResidualTier {
  label: string
  startMonth: number // inclusive (1-based)
  endMonth: number // inclusive
  rate: number // fraction of the corporate service fee
}

export const RESIDUAL_TIERS: ResidualTier[] = [
  { label: "Months 1–6", startMonth: 1, endMonth: 6, rate: 0.1 }, // 10%
  { label: "Months 7–12", startMonth: 7, endMonth: 12, rate: 0.065 }, // 6.5%
  { label: "Months 13–18", startMonth: 13, endMonth: 18, rate: 0.03 }, // 3%
]

export const RESIDUAL_WINDOW_MONTHS = 18

/** Return the residual rate that applies during a given (1-based) month. */
export function residualRateForMonth(month: number): number {
  const tier = RESIDUAL_TIERS.find((t) => month >= t.startMonth && month <= t.endMonth)
  return tier ? tier.rate : 0
}

/** Return the tier object active for a given month (or null past 18 months). */
export function tierForMonth(month: number): ResidualTier | null {
  return RESIDUAL_TIERS.find((t) => month >= t.startMonth && month <= t.endMonth) ?? null
}

/**
 * Whole months elapsed since an ISO start date (1-based, clamped at >= 0).
 * Month 1 = the first month after joining. Used to drive the 18-month clock.
 */
export function monthsActiveSince(startISO: string, now: number = Date.now()): number {
  const start = new Date(startISO).getTime()
  if (Number.isNaN(start) || now < start) return 0
  const elapsedMs = now - start
  const avgMonthMs = (365.25 / 12) * 24 * 60 * 60 * 1000
  return Math.max(1, Math.floor(elapsedMs / avgMonthMs) + 1)
}

// A revenue-producing account that a Bungee referred. Its monthly service fee
// is the 30% corporate fee generated by that account's transactions per month.
export interface ReferredAccount {
  id: string
  name: string
  type: "user" | "business"
  joinedAt: string // ISO — drives the 18-month residual clock
  monthlyServiceFee: number // $ of corporate service fee generated each month
}

export interface ResidualSummary {
  accountId: string
  name: string
  type: "user" | "business"
  monthsActive: number
  currentTier: ResidualTier | null
  currentMonthlyResidual: number // what the referrer earns this month
  accumulatedResidual: number // total earned to date across elapsed months
  projectedRemaining: number // residual still to come through month 18
  lifetimeProjected: number // full 18-month residual value
  isActive: boolean // still within the 18-month window
}

/**
 * Compute the residual a referrer has earned (and will earn) from one referred
 * account. Accumulates month-by-month so each month uses its correct tier rate.
 */
export function computeResidualForAccount(account: ReferredAccount, now: number = Date.now()): ResidualSummary {
  const monthsActive = monthsActiveSince(account.joinedAt, now)
  const monthlyFeeCents = toCents(account.monthlyServiceFee)

  let accumulatedCents = 0
  let lifetimeCents = 0

  for (let m = 1; m <= RESIDUAL_WINDOW_MONTHS; m++) {
    const rate = residualRateForMonth(m)
    const monthResidual = roundCents(monthlyFeeCents * rate)
    lifetimeCents += monthResidual
    if (m <= monthsActive) accumulatedCents += monthResidual
  }

  const currentTier = tierForMonth(monthsActive)
  const currentMonthlyCents = currentTier ? roundCents(monthlyFeeCents * currentTier.rate) : 0

  return {
    accountId: account.id,
    name: account.name,
    type: account.type,
    monthsActive,
    currentTier,
    currentMonthlyResidual: toDollars(currentMonthlyCents),
    accumulatedResidual: toDollars(accumulatedCents),
    projectedRemaining: toDollars(lifetimeCents - accumulatedCents),
    lifetimeProjected: toDollars(lifetimeCents),
    isActive: monthsActive <= RESIDUAL_WINDOW_MONTHS,
  }
}

export interface PortfolioTotals {
  accounts: ResidualSummary[]
  totalAccumulated: number
  totalMonthlyResidual: number
  totalProjectedRemaining: number
  totalLifetimeProjected: number
  activeCount: number
}

/** Aggregate residuals across every referred account a Bungee owns. */
export function computeResidualPortfolio(accounts: ReferredAccount[], now: number = Date.now()): PortfolioTotals {
  const summaries = accounts.map((a) => computeResidualForAccount(a, now))

  const sumCents = (pick: (s: ResidualSummary) => number) =>
    summaries.reduce((acc, s) => acc + toCents(pick(s)), 0)

  return {
    accounts: summaries,
    totalAccumulated: toDollars(sumCents((s) => s.accumulatedResidual)),
    totalMonthlyResidual: toDollars(sumCents((s) => s.currentMonthlyResidual)),
    totalProjectedRemaining: toDollars(sumCents((s) => s.projectedRemaining)),
    totalLifetimeProjected: toDollars(sumCents((s) => s.lifetimeProjected)),
    activeCount: summaries.filter((s) => s.isActive).length,
  }
}

/** Format a number as USD with exactly two decimals. */
export function formatCurrency(amount: number): string {
  return amount.toLocaleString("en-US", { style: "currency", currency: "USD", minimumFractionDigits: 2, maximumFractionDigits: 2 })
}

function isoMonthsAgo(months: number): string {
  const d = new Date()
  d.setMonth(d.getMonth() - months)
  return d.toISOString()
}

// Demo portfolio: referred accounts at different ages so each residual tier is
// represented (months 1–6, 7–12, 13–18, and one past the window).
export const demoReferredAccounts: ReferredAccount[] = [
  { id: "ra-1", name: "Elite HVAC Services", type: "business", joinedAt: isoMonthsAgo(2), monthlyServiceFee: 180 },
  { id: "ra-2", name: "BrightSmile Dental", type: "business", joinedAt: isoMonthsAgo(9), monthlyServiceFee: 120 },
  { id: "ra-3", name: "Marcus Pena", type: "user", joinedAt: isoMonthsAgo(15), monthlyServiceFee: 60 },
  { id: "ra-4", name: "GreenLeaf Landscaping", type: "business", joinedAt: isoMonthsAgo(4), monthlyServiceFee: 90 },
  { id: "ra-5", name: "Sofia Reyes", type: "user", joinedAt: isoMonthsAgo(20), monthlyServiceFee: 75 },
]
